apiVersion: extensions/v1
kind: Deployment
metadata:
  name: filebeat-test
  namespace: log
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: filebeat-test
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.8.3
        args: [ "-c", "/etc/filebeat.yml" ]
        volumeMounts:
        - name: app-logs
          mountPath: /log
        - name: filebeat-config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
      - name: app
        image: docker.elastic.co/beats/filebeat:6.8.3
        args: [ "-c", "/usr/share/filebeat/filebeat.yml" ]
        volumeMounts:
        - name: app-logs
          mountPath: /usr/share/filebeat/logs
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          defaultMode: 0644
          name: filebeat-config